version: '3'
services:
    sbb_postgres:
        container_name: sbb_postgres
        image: postgres:13.3
        environment:
            POSTGRES_DB: strapi
            POSTGRES_USER: strapi
            POSTGRES_PASSWORD: strapi
        ports:
            - '5432:5432'
        volumes:
            - ./db:/var/lib/postgresql/data
