[build]
	base = "frontend/"
	publish = ".next"
	command = "npm run build"

[functions]
	directory = "./utils/functions"

[context.branch-deploy]
  command = "npm run noIndex"

[[plugins]]
	package = "@netlify/plugin-nextjs"
[[plugins]]
	package = "/plugins/netlify-plugin-env-var-by-context"