[build]
	base = "frontend/"
	publish = "frontend/.next"
	command = "npm run build"
  ignore = "/bin/false"

[functions]
	directory = "./utils/functions"

[context.branch-deploy]
  command = "npm run noIndex"

[context.staging]
	command = "npm run noIndex"
