[build]
	base = "frontend/"
	publish = ".next"
	command = "npm run build"
  [build]
   ignore = "/bin/false"

[functions]
	directory = "./utils/functions"

[context.branch-deploy]
  command = "npm run noIndex"

[context.staging]
	command = "npm run noIndex"


[[plugins]]
	package = "@netlify/plugin-nextjs"
[[plugins]]
	package = 'netlify-plugin-contextual-env'
  [plugins.inputs]
  mode = 'prefix'
