[build]
	base = "frontend/"
	publish = ".next"
	command = "next build"

[[plugins]]
package = "@netlify/plugin-nextjs"
[[plugins]]
package = 'netlify-plugin-contextual-env'
  [plugins.inputs]
  mode = 'prefix'